---
- name: Install Ansible dependencies
  hosts: k3s_cluster
  gather_facts: false
  tasks:
  - name: Update APT cache
    raw: sudo apt-get update

  - name: Install Python3
    raw: sudo apt-get install -y python3

- name: Install cluster dependencies
  hosts: k3s_cluster
  become: true
  tasks:
  - name: Install iptables
    apt:
      name: iptables

  - name: Install Open-iSCSI
    apt:
      name: open-iscsi

  - name: Install NFSv4 client
    apt:
      name: nfs-common

  - name: Install XFS
    apt:
      name: xfsprogs

  - name: Disable SSH password authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*PasswordAuthentication\b(.*)$'
      line: PasswordAuthentication no
    notify:
    - Reload sshd

  - name: Set hostname
    hostname:
      name: "{{ ansible_host }}"

  - name: Set timezone
    timezone:
      name: Europe/Paris
      hwclock: UTC

  - name: Install NTP client
    apt:
      name: systemd-timesyncd

  handlers:
  - name: Reload sshd
    service:
      name: sshd
      state: reloaded

- name: Configure NAS machines
  hosts:
  - selfhosted
  - nas
  become: true
  tasks:
  - name: Format storage disks as XFS
    filesystem:
      dev: /dev/{{ item }}
      force: true
      fstype: xfs
      resizefs: true
    with_items: "{{ storage_disks }}"

  - name: Create storage mount points
    file:
      path: /mnt/{{ item }}
      state: directory
    with_items: "{{ storage_disks }}"

  - name: Mount storage disks
    mount:
      src: /dev/{{ item }}
      path: /mnt/{{ item }}
      fstype: xfs
      state: mounted
    with_items: "{{ storage_disks }}"

- name: Configure self-hosted machines
  hosts: selfhosted
  become: true
  tasks:
  - name: Update GRUB config for GPU passthrough
    lineinfile:
      dest: /etc/default/grub
      regexp: '^#?\s*GRUB_CMDLINE_LINUX_DEFAULT\s*=(.*)$'
      line: GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=efifb:off"
    notify:
    - Rebuild GRUB config

  - name: Load VFIO modules at boot
    lineinfile:
      dest: /etc/initramfs-tools/modules
      regexp: '^#?\s*{{ item }}\b.*$'
      line: "{{ item }}"
    with_items:
    - vfio_pci
    - vfio
    - vfio_iommu_type1
    - vfio_virqfd
    notify:
    - Update initramfs

  - name: List PCI devices
    shell: lspci -nn
    changed_when: false
    register: lspci

  - name: Get GPU device IDs
    set_fact:
      gpu_pci_ids: "{{ lspci.stdout_lines | map('regex_search', '^' + pci_gpu_filter + '\\[([0-9a-f:]+)\\]( \\([^)]+\\))?$', '\\1') | flatten }}"

  - name: Replace GPU drivers with VFIO
    copy:
      dest: /etc/modprobe.d/vfio.conf
      content: |
        softdep amdgpu pre: vfio-pci
        softdep radeon pre: vfio-pci
        softdep nouveau pre: vfio-pci
        softdep nvidia pre: vfio-pci
        softdep snd_intel_hda pre: vfio-pci

        options vfio-pci ids={{ gpu_pci_ids | join(',') }}
    notify:
    - Update initramfs

  handlers:
  - name: Rebuild GRUB config
    command: update-grub
    notify:
    - Reboot

  - name: Update initramfs
    command: update-initramfs -u
    notify:
    - Reboot

  - name: Reboot
    reboot:
