---
- name: Install Ansible dependencies
  hosts: k3s_cluster
  gather_facts: false
  tasks:
  - name: Update APT cache
    raw: sudo apt-get update

  - name: Install Python3
    raw: sudo apt-get install -y python3

- name: Install cluster dependencies
  hosts: k3s_cluster
  become: true
  tasks:
  - name: Install iptables
    apt:
      name: iptables

  - name: Install Open-iSCSI
    apt:
      name: open-iscsi

  - name: Install NFSv4 client
    apt:
      name: nfs-common

  - name: Install XFS
    apt:
      name: xfsprogs

  - name: Disable SSH password authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*PasswordAuthentication\b(.*)$'
      line: PasswordAuthentication no
    notify:
    - Reload sshd

  - name: Set hostname
    hostname:
      name: "{{ ansible_host }}"

  - name: Set timezone
    timezone:
      name: Europe/Paris
      hwclock: UTC

  - name: Install NTP client
    apt:
      name: systemd-timesyncd

  - name: Increase max_user_watches
    sysctl:
      name: fs.inotify.max_user_watches
      value: 524288

  - name: Increase max_user_instances
    sysctl:
      name: fs.inotify.max_user_instances
      value: 8192

  - name: Load NVMe TCP module
    modprobe:
      name: nvme_tcp
      persistent: present

  - name: Load NVMe core module
    modprobe:
      name: nvme_core
      persistent: present

  - name: Enabling NVMe multipathing
    copy:
      dest: /etc/modprobe.d/nvme_core.conf
      content: |
        options nvme_core multipath=Y
    notify:
    - Update initramfs

  handlers:
  - name: Reload sshd
    service:
      name: sshd
      state: reloaded

  - name: Update initramfs
    command: update-initramfs -u
    notify:
    - Reboot

  - name: Reboot
    reboot:

- name: Configure NAS machines
  hosts:
  - nas
  become: true
  tasks:
  - name: Add APT contrib repository
    apt_repository:
      filename: bullseye-contrib
      repo: deb http://deb.debian.org/debian/ bullseye contrib

  - name: Install ZFS
    apt:
      name: zfsutils-linux

  - name: Load ZFS module
    modprobe:
      name: zfs

  # TODO: Make idempotent
  # - name: Wipe storage disks
  #   command: wipefs -a /dev/disk/by-id/{{ item }}
  #   with_items: "{{ storage_disks }}"

  # - name: Create ZFS pool
  #   command: zpool create zfs-nas {{ storage_disks | join(' ') }}

- name: Configure self-hosted machines
  hosts: selfhosted
  become: true
  tasks:
  - name: Disable GRUB os-prober
    lineinfile:
      dest: /etc/default/grub
      regexp: '^#?\s*GRUB_DISABLE_OS_PROBER\s*=(.*)$'
      line: GRUB_DISABLE_OS_PROBER=true
    notify:
    - Rebuild GRUB config

  - name: Disable GRUB menu
    lineinfile:
      dest: /etc/default/grub
      regexp: '^#?\s*GRUB_TIMEOUT\s*=(.*)$'
      line: GRUB_TIMEOUT=0
    notify:
    - Rebuild GRUB config

  - name: Update Linux commandline for GPU passthrough
    lineinfile:
      dest: /etc/default/grub
      regexp: '^#?\s*GRUB_CMDLINE_LINUX_DEFAULT\s*=(.*)$'
      line: GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt video=efifb:off"
    notify:
    - Rebuild GRUB config

  - name: Load VFIO modules at boot
    lineinfile:
      dest: /etc/initramfs-tools/modules
      regexp: '^#?\s*{{ item }}\b.*$'
      line: "{{ item }}"
    with_items:
    - vfio_pci
    - vfio
    - vfio_iommu_type1
    - vfio_virqfd
    notify:
    - Update initramfs

  - name: List PCI devices
    shell: lspci -nn
    changed_when: false
    register: lspci

  - name: Get GPU device IDs
    set_fact:
      pci_passthrough_ids: "{{ lspci.stdout_lines | map('regex_search', '^' + pci_passthrough_filter + '\\[([0-9a-f:]+)\\]( \\([^)]+\\))?$', '\\1') | flatten }}"

  - name: Replace GPU drivers with VFIO
    copy:
      dest: /etc/modprobe.d/vfio.conf
      content: |
        softdep amdgpu pre: vfio-pci
        softdep radeon pre: vfio-pci
        softdep nouveau pre: vfio-pci
        softdep nvidia pre: vfio-pci
        softdep snd_hda_intel pre: vfio-pci
        softdep xhci_hcd pre: vfio-pci
        softdep xhci_pci pre: vfio-pci

        options vfio-pci ids={{ pci_passthrough_ids | join(',') }}
    notify:
    - Update initramfs

  - name: Disable Xbox controller's driver
    copy:
      dest: /etc/modprobe.d/xpad.conf
      content: |
        blacklist xpad
    notify:
    - Update initramfs

  - name: Disable game controllers' USB
    copy:
      dest: /etc/modprobe.d/usbhid.conf
      content: |
        options usbhid quirks=0x044f:0x0406:0x4 # Thrustmaster TCA Sidestick
        options usbhid quirks=0x044f:0x0407:0x4 # Thrustmaster TCA Quadrant
    notify:
    - Update initramfs

  - name: Format storage disks as XFS
    filesystem:
      dev: /dev/disk/by-id/{{ item }}
      force: true
      fstype: xfs
      resizefs: true
    with_items: "{{ storage_disks }}"

  - name: Create storage mount points
    file:
      path: /mnt/{{ item }}
      state: directory
    with_items: "{{ storage_disks }}"

  - name: Mount storage disks
    mount:
      src: /dev/disk/by-id/{{ item }}
      path: /mnt/{{ item }}
      fstype: xfs
      state: mounted
    with_items: "{{ storage_disks }}"

  handlers:
  - name: Rebuild GRUB config
    command: update-grub
    notify:
    - Reboot

  - name: Update initramfs
    command: update-initramfs -u
    notify:
    - Reboot

  - name: Reboot
    reboot:
